# This file based on https://gist.github.com/mwouts/9842452d020c08faf9e84a3bba38a66f
# See: https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
# 2020-06-22 - slg - customized
# 2020-06-27 - slg - expanded to G++ for MacOS
# 2020-07-03 - slg - ported to be13_api; removed python (be13_api doesn't use python)
# 2021-02-23 - ml - changed workflow triggers

name: Build tcpflow-gg
on:
  push:
    paths-ignore:
      - '.devcontainer/**'
    branches: master
  workflow_dispatch:

jobs:
  build-tcpflow-gg:
    runs-on: 'ubuntu-20.04'
    container:
      image: ghcr.io/${{ github.repository_owner }}/ethernet-proxy-dev:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build the executable
        run: |
          bash bootstrap.sh

          CC=${TOOLCHAIN}-gcc \
          CXX=${TOOLCHAIN}-g++ \
          AR=${TOOLCHAIN}-ar \
          STRIP=${TOOLCHAIN}-strip \
          RANLIB=${TOOLCHAIN}-ranlib \
          CPPFLAGS="" \
          LDFLAGS="" \
          ./configure \
              --host=arm-unknown-linux-gnueabi \
              --exec-prefix=$STAGING_DIR/usr/local \
              --prefix=${STAGING_DIR}/usr/local

          make

     # TODO: fix tests for cross-compilation and gg integration
     # - name: Run tests
     #   run: |
     #     make check

  upload-artifact-tcpflow-gg:
    runs-on: 'ubuntu-20.04'
    needs: build-tcpflow-gg

    steps:
      - name: Rename the binary
        working-directory: src
        run: |
          mv tcpflow_gg ethernetproxy-gg

      - name: Create greengrass deployment package
        working-directory: src
        run: |
          zip ethernetproxy-gg.zip ethernetproxy-gg
    
      - name: Upload Release Asset - Greengrass Deployment Package
        uses: actions/upload-artifact@v2
        with:
          name: greengrass-deployment-package
          path: |
            src/ethernetproxy-gg.zip